spring:
  application:
    name: todo

  config:
    import: "optional:file:.env[.properties]"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true